<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210621085211 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ds.sorttable DROP CONSTRAINT sorttable_list_id_fkey');
        $this->addSql('ALTER TABLE ds.sys_parameter DROP CONSTRAINT sys_parameter_category_id_fkey');
        $this->addSql('DROP SEQUENCE ds.people_to_duty_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.sorttable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.sorttable_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.sys_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.sys_parameter_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.table_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tlc.company_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE ds."group"_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.package_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.package_location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.quality_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.quality_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE ds.package (id INT NOT NULL, species_id CHAR(2) DEFAULT NULL, drec TIMESTAMP(0) WITH TIME ZONE NOT NULL, thickness SMALLINT DEFAULT NULL, width SMALLINT DEFAULT NULL, qualities VARCHAR(32) DEFAULT NULL, boards leam[] NOT NULL, dry BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5D50FBE3B2A1D860 ON ds.package (species_id)');
        $this->addSql('COMMENT ON TABLE ds.package IS \'Сформированные пакеты\'');
        $this->addSql('COMMENT ON COLUMN ds.package.drec IS \'Время формирования пакета\'');
        $this->addSql('COMMENT ON COLUMN ds.package.thickness IS \'Толщина\'');
        $this->addSql('COMMENT ON COLUMN ds.package.width IS \'Ширина\'');
        $this->addSql('COMMENT ON COLUMN ds.package.qualities IS \'Качество\'');
        $this->addSql('COMMENT ON COLUMN ds.package.boards IS \'Массив досок\'');
        $this->addSql('COMMENT ON COLUMN ds.package.dry IS \'Сухая или сырая\'');
        $this->addSql('CREATE TABLE ds.package_location (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON TABLE ds.package_location IS \'Локация пакета\'');
        $this->addSql('COMMENT ON COLUMN ds.package_location.name IS \'Название\'');
        $this->addSql('CREATE TABLE ds.package_move (drec VARCHAR(255) NOT NULL, src INT NOT NULL, dst INT NOT NULL, package_id INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, PRIMARY KEY(drec))');
        $this->addSql('CREATE INDEX IDX_EFA166636044248D ON ds.package_move (src)');
        $this->addSql('CREATE INDEX IDX_EFA16663E3E525FE ON ds.package_move (dst)');
        $this->addSql('CREATE INDEX IDX_EFA16663F44CABFF ON ds.package_move (package_id)');
        $this->addSql('COMMENT ON TABLE ds.package_move IS \'Информация о передвежениях\'');
        $this->addSql('COMMENT ON COLUMN ds.package_move.drec IS \'Время передвежения пакета\'');
        $this->addSql('CREATE TABLE people_to_duty (people_id INT NOT NULL, duty_id CHAR(2) NOT NULL, PRIMARY KEY(people_id, duty_id))');
        $this->addSql('CREATE INDEX IDX_2F76D123147C936 ON people_to_duty (people_id)');
        $this->addSql('CREATE INDEX IDX_2F76D123A1F9EC1 ON people_to_duty (duty_id)');
        $this->addSql('ALTER TABLE ds.package ADD CONSTRAINT FK_5D50FBE3B2A1D860 FOREIGN KEY (species_id) REFERENCES dic.species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.package_move ADD CONSTRAINT FK_EFA166636044248D FOREIGN KEY (src) REFERENCES ds.package_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.package_move ADD CONSTRAINT FK_EFA16663E3E525FE FOREIGN KEY (dst) REFERENCES ds.package_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.package_move ADD CONSTRAINT FK_EFA16663F44CABFF FOREIGN KEY (package_id) REFERENCES ds.package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_to_duty ADD CONSTRAINT FK_2F76D123147C936 FOREIGN KEY (people_id) REFERENCES ds.people (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_to_duty ADD CONSTRAINT FK_2F76D123A1F9EC1 FOREIGN KEY (duty_id) REFERENCES ds.duty (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE dic.board_length');
        $this->addSql('DROP TABLE dic.board_width');
        $this->addSql('DROP TABLE dic.gost_2708');
        $this->addSql('DROP TABLE dic.log_length');
        $this->addSql('DROP TABLE ds.people_to_duty');
        $this->addSql('DROP TABLE ds.sorttable_list');
        $this->addSql('DROP TABLE ds.sys_category');
        $this->addSql('DROP TABLE tlc.company');
        $this->addSql('DROP TABLE ds.sorttable');
        $this->addSql('DROP TABLE ds.sys_parameter');
        $this->addSql('DROP TABLE dic.board_thickness');
        $this->addSql('DROP INDEX group_dry_species_id_qualities_thickness_width_min_length_m_key');
        $this->addSql('DROP INDEX group_id_idx');
        $this->addSql('ALTER TABLE ds."group" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ds."group" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ds."group" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ds."group" ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX action_operator_id_key');
        $this->addSql('COMMENT ON COLUMN ds.action_operator.id IS NULL');
        $this->addSql('ALTER TABLE ds.action_operator ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT board_species_id_fkey');
        $this->addSql('ALTER TABLE ds.board ALTER drec TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ds.board ALTER drec DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.board.species_id IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_thickness IS \'Номинальная толщина\'');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_width IS \'Номинальная ширина\'');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_length IS \'Длина\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_1 IS \'ID доски, 1 бит\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_2 IS \'ID доски, 1 бит\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_1_name IS \'Название качества 1 операторa в момент записи\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_2_name IS \'Название качества 2 операторa в момент записи\'');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD10382FAEEFDEE FOREIGN KEY (nom_thickness) REFERENCES ds.thickness (nom) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD1038226E2D9BA FOREIGN KEY (nom_width) REFERENCES ds.width (nom) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD1038281B201E5 FOREIGN KEY (nom_length) REFERENCES ds.length (value) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD10382B2A1D860 FOREIGN KEY (species_id) REFERENCES dic.species (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD10382F034E435 FOREIGN KEY (quality_1) REFERENCES ds.quality (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT FK_4FD10382693DB58F FOREIGN KEY (quality_2) REFERENCES ds.quality (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4FD10382FAEEFDEE ON ds.board (nom_thickness)');
        $this->addSql('CREATE INDEX IDX_4FD1038226E2D9BA ON ds.board (nom_width)');
        $this->addSql('CREATE INDEX IDX_4FD1038281B201E5 ON ds.board (nom_length)');
        $this->addSql('CREATE INDEX IDX_4FD10382F034E435 ON ds.board (quality_1)');
        $this->addSql('CREATE INDEX IDX_4FD10382693DB58F ON ds.board (quality_2)');
        $this->addSql('ALTER TABLE ds.break_shedule DROP CONSTRAINT break_shedule_cause_id_fkey');
        $this->addSql('ALTER TABLE ds.break_shedule DROP CONSTRAINT break_shedule_place_id_fkey');
        $this->addSql('DROP INDEX break_shedule_start_stop_key');
        $this->addSql('COMMENT ON COLUMN ds.break_shedule.place_id IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.break_shedule.cause_id IS NULL');
        $this->addSql('ALTER TABLE ds.break_shedule ADD CONSTRAINT FK_814608AEDA6A219 FOREIGN KEY (place_id) REFERENCES ds.downtime_place (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.break_shedule ADD CONSTRAINT FK_814608AE66E2221E FOREIGN KEY (cause_id) REFERENCES ds.downtime_cause (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_814608AEB95616B6 ON ds.break_shedule (stop)');
        $this->addSql('ALTER TABLE ds.break_shedule ADD PRIMARY KEY (start)');
        $this->addSql('ALTER TABLE ds.downtime DROP CONSTRAINT downtime_cause_id_fkey');
        $this->addSql('ALTER TABLE ds.downtime DROP CONSTRAINT downtime_place_id_fkey');
        $this->addSql('COMMENT ON COLUMN ds.downtime.period IS \'Время начала простоя\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime.cause_id IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime.place_id IS NULL');
        $this->addSql('ALTER TABLE ds.downtime ADD CONSTRAINT FK_8B6D12BD66E2221E FOREIGN KEY (cause_id) REFERENCES ds.downtime_cause (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.downtime ADD CONSTRAINT FK_8B6D12BDDA6A219 FOREIGN KEY (place_id) REFERENCES ds.downtime_place (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.downtime_cause DROP CONSTRAINT downtime_cause_group_id_fkey');
        $this->addSql('ALTER TABLE ds.downtime_cause ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.downtime_cause.text IS \'Название причины\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime_cause.enabled IS \'Используется\'');
        $this->addSql('ALTER TABLE ds.downtime_cause ADD CONSTRAINT FK_E2BA8CD5FE54D947 FOREIGN KEY (group_id) REFERENCES ds.downtime_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX downtime_group_text_key');
        $this->addSql('ALTER TABLE ds.downtime_group ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.downtime_group.text IS \'Название причины\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime_group.enabled IS \'Используется\'');
        $this->addSql('DROP INDEX downtime_location_text_key');
        $this->addSql('ALTER TABLE ds.downtime_location ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.downtime_location.text IS \'Название причины\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime_location.enabled IS \'Используется\'');
        $this->addSql('ALTER TABLE ds.downtime_place DROP CONSTRAINT downtime_place_location_id_fkey');
        $this->addSql('ALTER TABLE ds.downtime_place ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.downtime_place.text IS \'Название места\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime_place.enabled IS \'Используется\'');
        $this->addSql('ALTER TABLE ds.downtime_place ADD CONSTRAINT FK_667DA0A764D218E FOREIGN KEY (location_id) REFERENCES ds.downtime_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX duty_name_key');
        $this->addSql('DROP INDEX duty_id_key');
        $this->addSql('ALTER TABLE ds.duty ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX error_id_key');
        $this->addSql('ALTER TABLE ds.error ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE ds.event DROP CONSTRAINT event_source_fkey');
        $this->addSql('ALTER TABLE ds.event DROP CONSTRAINT event_type_fkey');
        $this->addSql('DROP INDEX event_drec_key');
        $this->addSql('ALTER TABLE ds.event ALTER type TYPE VARCHAR(1)');
        $this->addSql('ALTER TABLE ds.event ALTER type SET NOT NULL');
        $this->addSql('ALTER TABLE ds.event ALTER source TYPE VARCHAR(1)');
        $this->addSql('ALTER TABLE ds.event ALTER source SET NOT NULL');
        $this->addSql('ALTER TABLE ds.event ALTER drec TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ds.event ALTER drec DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.event ALTER code SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN ds.event.drec IS \'Начало события\'');
        $this->addSql('COMMENT ON COLUMN ds.event.code IS NULL');
        $this->addSql('ALTER TABLE ds.event ADD CONSTRAINT FK_2C2922628CDE5729 FOREIGN KEY (type) REFERENCES ds.event_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.event ADD CONSTRAINT FK_2C2922625F8A7F73 FOREIGN KEY (source) REFERENCES ds.event_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.event ADD PRIMARY KEY (drec)');
        $this->addSql('ALTER INDEX ds.ind_event_event_id RENAME TO IDX_2C2922628CDE5729');
        $this->addSql('ALTER INDEX ds.ind_event_event_source RENAME TO IDX_2C2922625F8A7F73');
        $this->addSql('ALTER TABLE ds.event_source ALTER id TYPE VARCHAR(1)');
        $this->addSql('ALTER TABLE ds.event_source ALTER name TYPE VARCHAR(16)');
        $this->addSql('COMMENT ON COLUMN ds.event_source.name IS \'Название события\'');
        $this->addSql('ALTER TABLE ds.event_type ALTER id TYPE VARCHAR(1)');
        $this->addSql('COMMENT ON COLUMN ds.event_type.name IS NULL');
        $this->addSql('DROP INDEX length_value_key');
        $this->addSql('ALTER TABLE ds.length ADD PRIMARY KEY (value)');
        $this->addSql('DROP INDEX people_fam_nam_pat_key');
        $this->addSql('ALTER TABLE ds.people ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.people.fam IS \'Фамилия\'');
        $this->addSql('COMMENT ON COLUMN ds.people.nam IS \'Имя\'');
        $this->addSql('COMMENT ON COLUMN ds.people.pat IS \'Отчество\'');
        $this->addSql('DROP INDEX pocket_distance_pocket_key');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance.pocket IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance.integral IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance.decimal IS NULL');
        $this->addSql('ALTER TABLE ds.pocket_distance ADD PRIMARY KEY (pocket)');
        $this->addSql('ALTER TABLE ds.quality DROP CONSTRAINT quality_list_id_fkey');
        $this->addSql('DROP INDEX quality_list_id_name_idx');
        $this->addSql('DROP INDEX quality_id_list_id_key');
        $this->addSql('ALTER TABLE ds.quality ALTER list_id TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.quality ALTER list_id DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.quality ADD CONSTRAINT FK_FF8A97663DAE168B FOREIGN KEY (list_id) REFERENCES ds.quality_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.quality ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX quality_list_name_key');
        $this->addSql('DROP INDEX quality_list_id_key');
        $this->addSql('ALTER TABLE ds.quality_list ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE ds.shift DROP CONSTRAINT shift_people_id_fkey');
        $this->addSql('ALTER TABLE ds.shift ALTER people_id DROP NOT NULL');
        $this->addSql('ALTER TABLE ds.shift ALTER number TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.shift ALTER number DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.shift.period IS \'Время начала смены\'');
        $this->addSql('COMMENT ON COLUMN ds.shift.people_id IS NULL');
        $this->addSql('ALTER TABLE ds.shift ADD CONSTRAINT FK_B28C13803147C936 FOREIGN KEY (people_id) REFERENCES ds.people (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX shift_shedule_name_key');
        $this->addSql('DROP INDEX shift_shedule_start_key');
        $this->addSql('COMMENT ON COLUMN ds.shift_shedule.start IS \'Начало смены\'');
        $this->addSql('COMMENT ON COLUMN ds.shift_shedule.stop IS \'Конец смены\'');
        $this->addSql('ALTER TABLE ds.shift_shedule ADD PRIMARY KEY (start)');
        $this->addSql('ALTER INDEX ds.shift_shedule_stop_key RENAME TO UNIQ_95477672B95616B6');
        $this->addSql('DROP INDEX species_name_key');
        $this->addSql('DROP INDEX species_id_key');
        $this->addSql('ALTER TABLE dic.species ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX standard_length_standard_key');
        $this->addSql('ALTER TABLE ds.standard_length ADD range int2range NOT NULL');
        $this->addSql('ALTER TABLE ds.standard_length DROP minimum');
        $this->addSql('ALTER TABLE ds.standard_length DROP maximum');
        $this->addSql('ALTER TABLE ds.standard_length ALTER standard TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.standard_length ALTER standard DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.standard_length.range IS \'Диапазон фактических длин, мм\'');
        $this->addSql('ALTER TABLE ds.standard_length ADD PRIMARY KEY (standard)');
        $this->addSql('DROP INDEX thickness_nom_key');
        $this->addSql('ALTER TABLE ds.thickness ALTER min TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.thickness ALTER min DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.thickness ALTER max TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.thickness ALTER max DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.thickness ADD PRIMARY KEY (nom)');
        $this->addSql('DROP INDEX unload_drec_key');
        $this->addSql('ALTER TABLE ds.unload ALTER drec TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ds.unload ALTER drec DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.unload ALTER volume TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE ds.unload ALTER volume DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.unload.pocket IS \'Карман\'');
        $this->addSql('COMMENT ON COLUMN ds.unload."group" IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.unload.qualities IS \'Название качеств\'');
        $this->addSql('COMMENT ON COLUMN ds.unload.volume IS \'Объём выгруженного кармана\'');
        $this->addSql('ALTER TABLE ds.unload ADD PRIMARY KEY (drec)');
        $this->addSql('ALTER INDEX ds.idx_23747eeb988d0e7a RENAME TO IDX_23747EEB6DC044C5');
        $this->addSql('DROP INDEX vars_name_key');
        $this->addSql('COMMENT ON COLUMN ds.vars.name IS \'Ключ\'');
        $this->addSql('COMMENT ON COLUMN ds.vars.value IS \'Значение\'');
        $this->addSql('ALTER TABLE ds.vars ADD PRIMARY KEY (name)');
        $this->addSql('DROP INDEX width_nom_key');
        $this->addSql('ALTER TABLE ds.width ALTER min TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.width ALTER min DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.width ALTER max TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds.width ALTER max DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.width ADD PRIMARY KEY (nom)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA tlc');
        $this->addSql('ALTER TABLE ds.package_move DROP CONSTRAINT FK_EFA16663F44CABFF');
        $this->addSql('ALTER TABLE ds.package_move DROP CONSTRAINT FK_EFA166636044248D');
        $this->addSql('ALTER TABLE ds.package_move DROP CONSTRAINT FK_EFA16663E3E525FE');
        $this->addSql('DROP SEQUENCE ds."group"_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.package_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.package_location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.quality_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ds.quality_list_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE ds.people_to_duty_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.sorttable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.sorttable_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.sys_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.sys_parameter_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ds.table_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tlc.company_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE dic.board_length (length INT NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX board_length_length_key ON dic.board_length (length)');
        $this->addSql('CREATE TABLE dic.board_width (species_id CHAR(2) NOT NULL, nominal INT NOT NULL, saw NUMERIC(4, 1) NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX board_width_species_id_nominal_key ON dic.board_width (species_id, nominal)');
        $this->addSql('CREATE INDEX IDX_3A03FE90B2A1D860 ON dic.board_width (species_id)');
        $this->addSql('COMMENT ON TABLE dic.board_width IS \'Ширины досок\'');
        $this->addSql('COMMENT ON COLUMN dic.board_width.species_id IS \'Порода древесины\'');
        $this->addSql('COMMENT ON COLUMN dic.board_width.nominal IS \'Номинальный размер\'');
        $this->addSql('COMMENT ON COLUMN dic.board_width.saw IS \'Пильный размер\'');
        $this->addSql('CREATE TABLE dic.gost_2708 (diam SMALLINT NOT NULL, length SMALLINT NOT NULL, volume NUMERIC(7, 5) NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX gost_2708_idx ON dic.gost_2708 (diam, length)');
        $this->addSql('COMMENT ON TABLE dic.gost_2708 IS \'Лесоматериалы круглые. Таблица объёмов по ГОСТ 2708-75\'');
        $this->addSql('COMMENT ON COLUMN dic.gost_2708.diam IS \'Диаметр вершины в диапазоне 3 - 120 см.\'');
        $this->addSql('COMMENT ON COLUMN dic.gost_2708.length IS \'Длина в дипазоне 1 - 9.5 м.\'');
        $this->addSql('COMMENT ON COLUMN dic.gost_2708.volume IS \'Объём м³.\'');
        $this->addSql('CREATE TABLE dic.log_length (nom INT NOT NULL, min INT NOT NULL, max INT NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX log_length_nom_key ON dic.log_length (nom)');
        $this->addSql('COMMENT ON TABLE dic.log_length IS \'Длины брёвен\'');
        $this->addSql('COMMENT ON COLUMN dic.log_length.nom IS \'Номинальная длина, мм.\'');
        $this->addSql('COMMENT ON COLUMN dic.log_length.min IS \'Минимальная длина, мм.\'');
        $this->addSql('COMMENT ON COLUMN dic.log_length.max IS \'Максимальная длина, мм.\'');
        $this->addSql('CREATE TABLE ds.people_to_duty (id SERIAL NOT NULL, people_id INT NOT NULL, duty_id CHAR(2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX people_to_duty_people_id_duty_id_key ON ds.people_to_duty (people_id, duty_id)');
        $this->addSql('CREATE INDEX IDX_8956B4A93A1F9EC1 ON ds.people_to_duty (duty_id)');
        $this->addSql('CREATE INDEX IDX_8956B4A93147C936 ON ds.people_to_duty (people_id)');
        $this->addSql('COMMENT ON TABLE ds.people_to_duty IS \'Связующая таблица люди и должности\'');
        $this->addSql('CREATE TABLE ds.sorttable_list (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX sorttable_list_name_key ON ds.sorttable_list (name)');
        $this->addSql('CREATE TABLE ds.sys_category (id SERIAL NOT NULL, name VARCHAR(127) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX sys_category_name_key ON ds.sys_category (name)');
        $this->addSql('COMMENT ON TABLE ds.sys_category IS \'Категории системных параметров\'');
        $this->addSql('CREATE TABLE tlc.company (id SERIAL NOT NULL, name VARCHAR(128) DEFAULT NULL, address VARCHAR(256) DEFAULT NULL, boss VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON TABLE tlc.company IS \'Предприятия\'');
        $this->addSql('COMMENT ON COLUMN tlc.company.name IS \'Название предприятия\'');
        $this->addSql('COMMENT ON COLUMN tlc.company.address IS \'Адрес предприятия\'');
        $this->addSql('COMMENT ON COLUMN tlc.company.boss IS \'Руководитель предприятия\'');
        $this->addSql('CREATE TABLE ds.sorttable (id SERIAL NOT NULL, list_id INT NOT NULL, species_id CHAR(2) NOT NULL, ord SMALLINT NOT NULL, pocket SMALLINT DEFAULT 0 NOT NULL, dry BOOLEAN DEFAULT \'true\' NOT NULL, qualities INT DEFAULT 1 NOT NULL, thickness SMALLINT NOT NULL, width SMALLINT NOT NULL, min_length SMALLINT NOT NULL, max_length SMALLINT NOT NULL, capacity SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX sorttable_list_id_ord_key ON ds.sorttable (list_id, ord)');
        $this->addSql('CREATE INDEX IDX_7D7F2D003DAE168B ON ds.sorttable (list_id)');
        $this->addSql('CREATE INDEX IDX_7D7F2D00B2A1D860 ON ds.sorttable (species_id)');
        $this->addSql('COMMENT ON TABLE ds.sorttable IS \'Строки сортировочных таблиц\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.species_id IS \'Порода\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.ord IS \'Порядок сортировки\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.pocket IS \'Карман доски\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.dry IS \'Сухая или сырая\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.qualities IS \'Качества\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.thickness IS \'Толщина\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.width IS \'Ширина\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.min_length IS \'Минимальная длина\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.max_length IS \'Максимальная длина\'');
        $this->addSql('COMMENT ON COLUMN ds.sorttable.capacity IS \'Вместимость кармана\'');
        $this->addSql('CREATE TABLE ds.sys_parameter (id SERIAL NOT NULL, category_id INT NOT NULL, name VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, db INT NOT NULL, "offset" INT NOT NULL, min INT DEFAULT NULL, max INT DEFAULT NULL, value INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX sys_parameter_category_id_name_key ON ds.sys_parameter (category_id, name)');
        $this->addSql('CREATE INDEX IDX_4D89D07E12469DE2 ON ds.sys_parameter (category_id)');
        $this->addSql('COMMENT ON TABLE ds.sys_parameter IS \'Системные параметры\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.name IS \'Имя системного параметра\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.type IS \'Тип ситемного параметра см. SysPar.h\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.db IS \'Номер DB в Simatic PLC\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter."offset" IS \'Смещение в DB в Simatic PLC\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.min IS \'Минимальное значение параметра\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.max IS \'Максимальное значение параметра\'');
        $this->addSql('COMMENT ON COLUMN ds.sys_parameter.value IS \'Значение параметра\'');
        $this->addSql('CREATE TABLE dic.board_thickness (species_id CHAR(2) NOT NULL, nominal INT NOT NULL, saw NUMERIC(4, 1) NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX board_thickness_species_id_nominal_key ON dic.board_thickness (species_id, nominal)');
        $this->addSql('CREATE INDEX IDX_5B077C33B2A1D860 ON dic.board_thickness (species_id)');
        $this->addSql('COMMENT ON TABLE dic.board_thickness IS \'Ширины досок\'');
        $this->addSql('COMMENT ON COLUMN dic.board_thickness.species_id IS \'Порода древесины\'');
        $this->addSql('COMMENT ON COLUMN dic.board_thickness.nominal IS \'Номинальный размер\'');
        $this->addSql('COMMENT ON COLUMN dic.board_thickness.saw IS \'Пильный размер\'');
        $this->addSql('ALTER TABLE dic.board_width ADD CONSTRAINT board_width_species_id_fkey FOREIGN KEY (species_id) REFERENCES dic.species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.people_to_duty ADD CONSTRAINT people_to_duty_duty_id_fkey FOREIGN KEY (duty_id) REFERENCES ds.duty (id) ON UPDATE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.people_to_duty ADD CONSTRAINT people_to_duty_people_id_fkey FOREIGN KEY (people_id) REFERENCES ds.people (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.sorttable ADD CONSTRAINT sorttable_list_id_fkey FOREIGN KEY (list_id) REFERENCES ds.sorttable_list (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.sorttable ADD CONSTRAINT sorttable_species_id_fkey FOREIGN KEY (species_id) REFERENCES dic.species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.sys_parameter ADD CONSTRAINT sys_parameter_category_id_fkey FOREIGN KEY (category_id) REFERENCES ds.sys_category (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dic.board_thickness ADD CONSTRAINT board_thickness_species_id_fkey FOREIGN KEY (species_id) REFERENCES dic.species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE ds.package');
        $this->addSql('DROP TABLE ds.package_location');
        $this->addSql('DROP TABLE ds.package_move');
        $this->addSql('DROP TABLE people_to_duty');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD10382FAEEFDEE');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD1038226E2D9BA');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD1038281B201E5');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD10382B2A1D860');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD10382F034E435');
        $this->addSql('ALTER TABLE ds.board DROP CONSTRAINT FK_4FD10382693DB58F');
        $this->addSql('DROP INDEX IDX_4FD10382FAEEFDEE');
        $this->addSql('DROP INDEX IDX_4FD1038226E2D9BA');
        $this->addSql('DROP INDEX IDX_4FD1038281B201E5');
        $this->addSql('DROP INDEX IDX_4FD10382F034E435');
        $this->addSql('DROP INDEX IDX_4FD10382693DB58F');
        $this->addSql('ALTER TABLE ds.board ALTER drec TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE ds.board ALTER drec SET DEFAULT \'now()\'');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_thickness IS \'Номинальная толщина доски, мм.\'');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_width IS \'Номинальная ширина доски, мм.\'');
        $this->addSql('COMMENT ON COLUMN ds.board.nom_length IS \'Номинальная длина доски, мм.\'');
        $this->addSql('COMMENT ON COLUMN ds.board.species_id IS \'Порода\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_1 IS \'Два качества от операторов, по 4 бита\'');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_2 IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_1_name IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.board.quality_2_name IS NULL');
        $this->addSql('ALTER TABLE ds.board ADD CONSTRAINT board_species_id_fkey FOREIGN KEY (species_id) REFERENCES dic.species (id) ON UPDATE CASCADE ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE ds.people_id_seq');
        $this->addSql('SELECT setval(\'ds.people_id_seq\', (SELECT MAX(id) FROM ds.people))');
        $this->addSql('ALTER TABLE ds.people ALTER id SET DEFAULT nextval(\'ds.people_id_seq\')');
        $this->addSql('COMMENT ON COLUMN ds.people.fam IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.people.nam IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.people.pat IS NULL');
        $this->addSql('CREATE UNIQUE INDEX people_fam_nam_pat_key ON ds.people (fam, nam, pat)');
        $this->addSql('ALTER TABLE ds.downtime_cause DROP CONSTRAINT FK_E2BA8CD5FE54D947');
        $this->addSql('CREATE SEQUENCE ds.downtime_cause_id_seq');
        $this->addSql('SELECT setval(\'ds.downtime_cause_id_seq\', (SELECT MAX(id) FROM ds.downtime_cause))');
        $this->addSql('ALTER TABLE ds.downtime_cause ALTER id SET DEFAULT nextval(\'ds.downtime_cause_id_seq\')');
        $this->addSql('COMMENT ON COLUMN ds.downtime_cause.text IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime_cause.enabled IS NULL');
        $this->addSql('ALTER TABLE ds.downtime_cause ADD CONSTRAINT downtime_cause_group_id_fkey FOREIGN KEY (group_id) REFERENCES ds.downtime_group (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('COMMENT ON COLUMN ds.action_operator.id IS \'Код дейсвия\'');
        $this->addSql('CREATE UNIQUE INDEX action_operator_id_key ON ds.action_operator (id)');
        $this->addSql('ALTER TABLE ds.break_shedule DROP CONSTRAINT FK_814608AEDA6A219');
        $this->addSql('ALTER TABLE ds.break_shedule DROP CONSTRAINT FK_814608AE66E2221E');
        $this->addSql('DROP INDEX UNIQ_814608AEB95616B6');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('COMMENT ON COLUMN ds.break_shedule.place_id IS \'Место простоя\'');
        $this->addSql('COMMENT ON COLUMN ds.break_shedule.cause_id IS \'Причина простоя\'');
        $this->addSql('ALTER TABLE ds.break_shedule ADD CONSTRAINT break_shedule_cause_id_fkey FOREIGN KEY (cause_id) REFERENCES ds.downtime_cause (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.break_shedule ADD CONSTRAINT break_shedule_place_id_fkey FOREIGN KEY (place_id) REFERENCES ds.downtime_place (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX break_shedule_start_stop_key ON ds.break_shedule (start, stop)');
        $this->addSql('ALTER TABLE ds.downtime_place DROP CONSTRAINT FK_667DA0A764D218E');
        $this->addSql('CREATE SEQUENCE ds.downtime_place_id_seq');
        $this->addSql('SELECT setval(\'ds.downtime_place_id_seq\', (SELECT MAX(id) FROM ds.downtime_place))');
        $this->addSql('ALTER TABLE ds.downtime_place ALTER id SET DEFAULT nextval(\'ds.downtime_place_id_seq\')');
        $this->addSql('COMMENT ON COLUMN ds.downtime_place.text IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime_place.enabled IS NULL');
        $this->addSql('ALTER TABLE ds.downtime_place ADD CONSTRAINT downtime_place_location_id_fkey FOREIGN KEY (location_id) REFERENCES ds.downtime_location (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE ds.downtime_location_id_seq');
        $this->addSql('SELECT setval(\'ds.downtime_location_id_seq\', (SELECT MAX(id) FROM ds.downtime_location))');
        $this->addSql('ALTER TABLE ds.downtime_location ALTER id SET DEFAULT nextval(\'ds.downtime_location_id_seq\')');
        $this->addSql('COMMENT ON COLUMN ds.downtime_location.text IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime_location.enabled IS NULL');
        $this->addSql('CREATE UNIQUE INDEX downtime_location_text_key ON ds.downtime_location (text)');
        $this->addSql('CREATE SEQUENCE ds.downtime_group_id_seq');
        $this->addSql('SELECT setval(\'ds.downtime_group_id_seq\', (SELECT MAX(id) FROM ds.downtime_group))');
        $this->addSql('ALTER TABLE ds.downtime_group ALTER id SET DEFAULT nextval(\'ds.downtime_group_id_seq\')');
        $this->addSql('COMMENT ON COLUMN ds.downtime_group.text IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime_group.enabled IS NULL');
        $this->addSql('CREATE UNIQUE INDEX downtime_group_text_key ON ds.downtime_group (text)');
        $this->addSql('ALTER TABLE ds.event_source ALTER id TYPE CHAR(1)');
        $this->addSql('ALTER TABLE ds.event_source ALTER name TYPE VARCHAR(32)');
        $this->addSql('COMMENT ON COLUMN ds.event_source.name IS NULL');
        $this->addSql('ALTER TABLE ds.event DROP CONSTRAINT FK_2C2922628CDE5729');
        $this->addSql('ALTER TABLE ds.event DROP CONSTRAINT FK_2C2922625F8A7F73');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.event ALTER drec TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE ds.event ALTER drec SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE ds.event ALTER type TYPE CHAR(1)');
        $this->addSql('ALTER TABLE ds.event ALTER type DROP NOT NULL');
        $this->addSql('ALTER TABLE ds.event ALTER source TYPE CHAR(1)');
        $this->addSql('ALTER TABLE ds.event ALTER source DROP NOT NULL');
        $this->addSql('ALTER TABLE ds.event ALTER code DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN ds.event.drec IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.event.code IS \'Код события\'');
        $this->addSql('ALTER TABLE ds.event ADD CONSTRAINT event_source_fkey FOREIGN KEY (source) REFERENCES ds.event_source (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.event ADD CONSTRAINT event_type_fkey FOREIGN KEY (type) REFERENCES ds.event_type (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX event_drec_key ON ds.event (drec)');
        $this->addSql('ALTER INDEX ds.idx_2c2922628cde5729 RENAME TO ind_event_event_id');
        $this->addSql('ALTER INDEX ds.idx_2c2922625f8a7f73 RENAME TO ind_event_event_source');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('CREATE UNIQUE INDEX error_id_key ON ds.error (id)');
        $this->addSql('ALTER TABLE ds.event_type ALTER id TYPE CHAR(1)');
        $this->addSql('COMMENT ON COLUMN ds.event_type.name IS \'Название типа\'');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds."group" ALTER id TYPE SMALLINT');
        $this->addSql('ALTER TABLE ds."group" ALTER id DROP DEFAULT');
        $this->addSql('CREATE SEQUENCE ds."group"_id_seq');
        $this->addSql('SELECT setval(\'ds."group"_id_seq\', (SELECT MAX(id) FROM ds."group"))');
        $this->addSql('ALTER TABLE ds."group" ALTER id SET DEFAULT nextval(\'ds."group"_id_seq\')');
        $this->addSql('CREATE UNIQUE INDEX group_dry_species_id_qualities_thickness_width_min_length_m_key ON ds."group" (dry, species_id, qualities, thickness, width, min_length, max_length)');
        $this->addSql('CREATE UNIQUE INDEX group_id_idx ON ds."group" (id)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('CREATE UNIQUE INDEX duty_name_key ON ds.duty (name)');
        $this->addSql('CREATE UNIQUE INDEX duty_id_key ON ds.duty (id)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('CREATE UNIQUE INDEX length_value_key ON ds.length (value)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('CREATE UNIQUE INDEX quality_list_name_key ON ds.quality_list (name)');
        $this->addSql('CREATE UNIQUE INDEX quality_list_id_key ON ds.quality_list (id)');
        $this->addSql('ALTER TABLE ds.quality DROP CONSTRAINT FK_FF8A97663DAE168B');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.quality ALTER list_id TYPE INT');
        $this->addSql('ALTER TABLE ds.quality ALTER list_id DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.quality ADD CONSTRAINT quality_list_id_fkey FOREIGN KEY (list_id) REFERENCES ds.quality_list (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX quality_list_id_name_idx ON ds.quality (list_id, name)');
        $this->addSql('CREATE UNIQUE INDEX quality_id_list_id_key ON ds.quality (id, list_id)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance.pocket IS \'Карман\'');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance.integral IS \'Расстояние, целые\'');
        $this->addSql('COMMENT ON COLUMN ds.pocket_distance."decimal" IS \'Расстояние, десятые\'');
        $this->addSql('CREATE UNIQUE INDEX pocket_distance_pocket_key ON ds.pocket_distance (pocket)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('COMMENT ON COLUMN ds.shift_shedule.start IS \'Начало смeны\'');
        $this->addSql('COMMENT ON COLUMN ds.shift_shedule.stop IS \'Конец смeны\'');
        $this->addSql('CREATE UNIQUE INDEX shift_shedule_name_key ON ds.shift_shedule (name)');
        $this->addSql('CREATE UNIQUE INDEX shift_shedule_start_key ON ds.shift_shedule (start)');
        $this->addSql('ALTER INDEX ds.uniq_95477672b95616b6 RENAME TO shift_shedule_stop_key');
        $this->addSql('ALTER TABLE ds.shift DROP CONSTRAINT FK_B28C13803147C936');
        $this->addSql('ALTER TABLE ds.shift ALTER people_id SET NOT NULL');
        $this->addSql('ALTER TABLE ds.shift ALTER number TYPE INT');
        $this->addSql('ALTER TABLE ds.shift ALTER number DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.shift.period IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.shift.people_id IS \'ID оператора\'');
        $this->addSql('ALTER TABLE ds.shift ADD CONSTRAINT shift_people_id_fkey FOREIGN KEY (people_id) REFERENCES ds.people (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.downtime DROP CONSTRAINT FK_8B6D12BD66E2221E');
        $this->addSql('ALTER TABLE ds.downtime DROP CONSTRAINT FK_8B6D12BDDA6A219');
        $this->addSql('COMMENT ON COLUMN ds.downtime.period IS NULL');
        $this->addSql('COMMENT ON COLUMN ds.downtime.cause_id IS \'Причина простоя\'');
        $this->addSql('COMMENT ON COLUMN ds.downtime.place_id IS \'Место простоя\'');
        $this->addSql('ALTER TABLE ds.downtime ADD CONSTRAINT downtime_cause_id_fkey FOREIGN KEY (cause_id) REFERENCES ds.downtime_cause (id) ON UPDATE CASCADE ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ds.downtime ADD CONSTRAINT downtime_place_id_fkey FOREIGN KEY (place_id) REFERENCES ds.downtime_place (id) ON UPDATE CASCADE ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.standard_length ADD minimum INT NOT NULL');
        $this->addSql('ALTER TABLE ds.standard_length ADD maximum INT NOT NULL');
        $this->addSql('ALTER TABLE ds.standard_length DROP range');
        $this->addSql('ALTER TABLE ds.standard_length ALTER standard TYPE INT');
        $this->addSql('ALTER TABLE ds.standard_length ALTER standard DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.standard_length.minimum IS \'РњРёРЅРёРјР°Р»СЊРЅР°СЏ РіСЂР°РЅРёС†Р° РґРёР°РїР°Р·РѕРЅР° РЅРµ РІРєР»СЋС‡Р°СЏ, РјРј.\'');
        $this->addSql('COMMENT ON COLUMN ds.standard_length.maximum IS \'РњР°РєСЃРёРјР°Р»СЊРЅР°СЏ РіСЂР°РЅРёС†Р° РґРёР°РїР°Р·РѕРЅР° РІРєР»СЋС‡Р°СЏ, РјРј.\'');
        $this->addSql('CREATE UNIQUE INDEX standard_length_standard_key ON ds.standard_length (standard)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.unload ALTER drec TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE ds.unload ALTER drec SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE ds.unload ALTER volume TYPE NUMERIC(6, 3)');
        $this->addSql('ALTER TABLE ds.unload ALTER volume DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN ds.unload."group" IS \'Группа\'');
        $this->addSql('COMMENT ON COLUMN ds.unload.qualities IS \'Названия качеств\'');
        $this->addSql('COMMENT ON COLUMN ds.unload.pocket IS \'Номер выгруженного кармана\'');
        $this->addSql('COMMENT ON COLUMN ds.unload.volume IS \'Объём досок\'');
        $this->addSql('CREATE UNIQUE INDEX unload_drec_key ON ds.unload (drec)');
        $this->addSql('ALTER INDEX ds.idx_23747eeb6dc044c5 RENAME TO IDX_23747EEB988D0E7A');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.thickness ALTER min TYPE NUMERIC(4, 1)');
        $this->addSql('ALTER TABLE ds.thickness ALTER min DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.thickness ALTER max TYPE NUMERIC(4, 1)');
        $this->addSql('ALTER TABLE ds.thickness ALTER max DROP DEFAULT');
        $this->addSql('CREATE UNIQUE INDEX thickness_nom_key ON ds.thickness (nom)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('COMMENT ON COLUMN ds.vars.name IS \'Имя переменной\'');
        $this->addSql('COMMENT ON COLUMN ds.vars.value IS \'Значение переменной\'');
        $this->addSql('CREATE UNIQUE INDEX vars_name_key ON ds.vars (name)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('ALTER TABLE ds.width ALTER min TYPE NUMERIC(4, 1)');
        $this->addSql('ALTER TABLE ds.width ALTER min DROP DEFAULT');
        $this->addSql('ALTER TABLE ds.width ALTER max TYPE NUMERIC(4, 1)');
        $this->addSql('ALTER TABLE ds.width ALTER max DROP DEFAULT');
        $this->addSql('CREATE UNIQUE INDEX width_nom_key ON ds.width (nom)');
        $this->addSql('DROP INDEX "primary"');
        $this->addSql('CREATE UNIQUE INDEX species_name_key ON dic.species (name)');
        $this->addSql('CREATE UNIQUE INDEX species_id_key ON dic.species (id)');
    }
}
